[Unit]
Requires=nftables.service onionroute-tor-secret-agent.service
After=nftables.service network-online.target onionroute-tor-secret-agent.service

[Service]
NoNewPrivileges=yes
CapabilityBoundingSet=
AmbientCapabilities=
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
RestrictAddressFamilies=AF_UNIX AF_INET
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
IPAddressDeny=169.254.0.0/16
IPAddressDeny=100.100.100.200/32
IPAddressDeny=168.63.129.16/32
ExecStartPre=/usr/local/libexec/onionroute-wait-secret /run/onionroute/secrets/onion/data/hs_ed25519_secret_key 90
ExecStartPre=/usr/local/libexec/onionroute-wait-secret /run/onionroute/secrets/onion/management/hs_ed25519_secret_key 90
ReadWritePaths=/var/lib/tor /run/tor /run/onionroute/secrets/onion
StandardOutput=null
StandardError=null
